run:
  timeout: 5m
  issues-exit-code: 1
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet